try {
    console.log("goodbye world");
} catch (e) {
    console.log("exception, yo");
} finally {
    console.log("hello world");
}
